//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZapFood.WinForm {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Instalacao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Instalacao() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZapFood.WinForm.Instalacao", typeof(Instalacao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a if not exists (select * from dbo.sysobjects where id = object_id(N&apos;[dbo].AccessToken&apos;) and 
        ///                                       OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///                                    BEGIN
        ///	                                    Create Table AccessToken(
        ///		                                    access_token Varchar(8000),
        ///		                                    token_type	Varchar(25),
        ///		                                    expires_in	int,
        ///		                                    scope Varchar(50 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string AccessToken {
            get {
                return ResourceManager.GetString("AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a if not exists (select * from dbo.sysobjects where id = object_id(N&apos;[dbo].VapVupVersao&apos;) and 
        ///	OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///BEGIN
        ///	Create Table VapVupVersao(
        ///		VersaoId uniqueidentifier not null,
        ///		DataInstalacao DateTime,
        ///		VersaoAtual varchar(50),
        ///		DataAtualizacao DateTime
        ///	)
        ///End.
        /// </summary>
        internal static string CreateTableVapVupVersao {
            get {
                return ResourceManager.GetString("CreateTableVapVupVersao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a if not exists (select * from dbo.sysobjects where id = object_id(N&apos;[dbo].PedidoVapVupt&apos;) and OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///                        BEGIN
        ///	                        CREATE TABLE [dbo].[PedidoVapVupt](
        ///		                        [VapVuptId] [uniqueidentifier] NOT NULL,
        ///		                        [PedidoId] [varchar](100) NULL,
        ///		                        [VendaId] [varchar](50) NULL,
        ///		                        [DataHora] [datetime] NULL,
        ///		                        [Situacao] [int] NULL
        ///	     [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string PedidoVapVupt {
            get {
                return ResourceManager.GetString("PedidoVapVupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a if not exists(select name from syscolumns where name = &apos;FileJson&apos; and id = OBJECT_ID(N&apos;PedidoVapVupt&apos;) )
        ///   Alter Table PedidoVapVupt Add FileJson Varchar(max)
        ///
        ///if not exists(select name from syscolumns where name = &apos;Aplicacao&apos; and id = OBJECT_ID(N&apos;PedidoVapVupt&apos;) )
        ///   Alter Table PedidoVapVupt Add Aplicacao Int
        ///
        ///if not exists(select name from syscolumns where name = &apos;TipoPedido&apos; and id = OBJECT_ID(N&apos;PedidoVapVupt&apos;) )
        ///   Alter Table PedidoVapVupt Add TipoPedido Varchar(25).
        /// </summary>
        internal static string ScriptUpdate {
            get {
                return ResourceManager.GetString("ScriptUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select 1 from dbo.sysobjects where id = object_id(N&apos;[dbo].AccessToken&apos;) and
        ///                                       OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1.
        /// </summary>
        internal static string VerificaInstalacao {
            get {
                return ResourceManager.GetString("VerificaInstalacao", resourceCulture);
            }
        }
    }
}
